version: '3.7'
services:
  rstudio:
    image: rocker/rstudio
    container_name: objRstudio
    # expose port
    ports:
      - 80:8787
    volumes:
      #
      # volume cannot be /root/rstudio
      # change permissions of uploaded R files
      # addmod rstudio to sudo group
      - /root/rstudio/R:/home/rstudio/R:rw
    environment:
      - PASSWORD=password   # required
#      - USER=               # default user=rstudio
#      - ROOT=TRUE           # give root permission
#      - ADD=shiny           # add shiny server
#      - DISABLE_AUTH=true   # disable password