version: '3.7'
services:
  couchdb:
    # latest, 2.3.1
    image: couchdb
    container_name: objCouchDb
    # expose port
    ports:
      - 5984:5984
    # (optional) opt/couchdb/etc/local.ini
    volumes:
      - /root/couchdb/data:/opt/couchdb/data:rw
      - /root/couchdb/log:/opt/couchdb/log:rw
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  caddy:
    # navigate to http://127.0.0.1/ for Caddy
    # alternative Caddy v1 abiosoft/caddy
    image: abiosoft/caddy
    container_name: objCaddy
    # expose port
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/couchdb/Caddyfile:/etc/Caddyfile:rw
      - /root/couchdb/.caddy:/root/.caddy:rw
    depends_on: 
      - couchdb
