version: '3.7'
services:
  couchdb:
    # latest, 2.3.1
    image: couchdb
    container_name: objCouchDb
    # expose port
    ports:
      - 5984:5984
    # (optional) opt/couchdb/etc/local.ini
    volumes:
      - /root/couchdb/data:/opt/couchdb/data:rw
      - /root/couchdb/log:/opt/couchdb/log:rw
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
