version: '3.7'
services:

  postgres:
    image: postgres:12.2
    restart: always
    volumes:
      - /root/guacamole/init:/docker-entrypoint-initdb.d
      - /root/guacamole/data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db

  guacd:
    image: guacamole/guacd:1.1.0
    restart: always

  guac:
    # navigate to http://127.0.0.1/guacamole for UI
    # default user/pass guacadmin/guacadmin
    image: guacamole/guacamole:1.1.0
    restart: always
    ports:
      - "80:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
